/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddNew: typeof import('./src/components/icons/addNew.vue')['default']
    AiItem: typeof import('./src/components/AiItem.vue')['default']
    Cancel: typeof import('./src/components/icons/cancel.vue')['default']
    GroupDrawer: typeof import('./src/components/GroupDrawer.vue')['default']
    GroupIcon: typeof import('./src/components/GroupIcon.vue')['default']
    GroupItem: typeof import('./src/components/GroupItem.vue')['default']
    ImageUpload: typeof import('./src/components/ImageUpload.vue')['default']
    Jseditor: typeof import('./src/components/icons/jseditor.vue')['default']
    JsEditorDrawer: typeof import('./src/components/JsEditorDrawer.vue')['default']
    LeftMenu: typeof import('./src/components/LeftMenu.vue')['default']
    LinkItem: typeof import('./src/components/LinkItem.vue')['default']
    NAlert: typeof import('naive-ui')['NAlert']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NDrawerContent: typeof import('naive-ui')['NDrawerContent']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NewDrawer: typeof import('./src/components/NewDrawer.vue')['default']
    NFlex: typeof import('naive-ui')['NFlex']
    NH3: typeof import('naive-ui')['NH3']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NInputGroup: typeof import('naive-ui')['NInputGroup']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NP: typeof import('naive-ui')['NP']
    NPopover: typeof import('naive-ui')['NPopover']
    NRadioButton: typeof import('naive-ui')['NRadioButton']
    NRadioGroup: typeof import('naive-ui')['NRadioGroup']
    NSpace: typeof import('naive-ui')['NSpace']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NTag: typeof import('naive-ui')['NTag']
    NText: typeof import('naive-ui')['NText']
    Options: typeof import('./src/components/icons/options.vue')['default']
    Options1: typeof import('./src/components/icons/options1.vue')['default']
    Refresh: typeof import('./src/components/icons/refresh.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Save: typeof import('./src/components/icons/save.vue')['default']
    ShortItem: typeof import('./src/components/ShortItem.vue')['default']
  }
}
